-- MySQL Script generated by MySQL Workbench
-- Fri Oct 26 19:00:44 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema cuestionario
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema cuestionario
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `cuestionario` DEFAULT CHARACTER SET utf8 ;
USE `cuestionario` ;

-- -----------------------------------------------------
-- Table `cuestionario`.`Usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cuestionario`.`Usuario` (
  `idUsuario` INT NOT NULL,
  `Nick` VARCHAR(45) NULL,
  `Contraseña` VARCHAR(45) NULL,
  `Nombre` VARCHAR(45) NULL,
  `Apellido` VARCHAR(45) NULL,
  `Email` VARCHAR(45) NULL,
  `Telf` VARCHAR(45) NULL,
  `Tipo_Usuario` VARCHAR(45) NULL,
  `Validacion` TINYINT(1) NULL,
  PRIMARY KEY (`idUsuario`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cuestionario`.`Curso`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cuestionario`.`Curso` (
  `idCurso` INT NOT NULL,
  `Nombre` VARCHAR(45) NULL,
  `Desc_Cat` VARCHAR(45) NULL,
  PRIMARY KEY (`idCurso`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cuestionario`.`Tema`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cuestionario`.`Tema` (
  `idTema` INT NOT NULL,
  `Nombre` VARCHAR(45) NULL,
  `idCurso` INT NOT NULL,
  PRIMARY KEY (`idTema`),
  INDEX `fk_Temas_Varios_Cursos_Varios1_idx` (`idCurso` ASC) VISIBLE,
  CONSTRAINT `fk_Temas_Varios_Cursos_Varios1`
    FOREIGN KEY (`idCurso`)
    REFERENCES `cuestionario`.`Curso` (`idCurso`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cuestionario`.`Preguntas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cuestionario`.`Preguntas` (
  `idPreguntas` INT NOT NULL,
  `Desc_Preg` VARCHAR(45) NULL,
  `Tiempo` VARCHAR(45) NULL,
  `Imagen` VARCHAR(45) NULL,
  `Puntaje` VARCHAR(45) NULL,
  `idTemas_Varios` INT NOT NULL,
  `Nivel` VARCHAR(45) NOT NULL,
  `Num_Intento` VARCHAR(45) NULL,
  `Comodin` VARCHAR(45) NOT NULL,
  `tipo_pregunta` VARCHAR(45) NULL,
  PRIMARY KEY (`idPreguntas`),
  INDEX `fk_Preguntas_Temas_Varios1_idx` (`idTemas_Varios` ASC) VISIBLE,
  CONSTRAINT `fk_Preguntas_Temas_Varios1`
    FOREIGN KEY (`idTemas_Varios`)
    REFERENCES `cuestionario`.`Tema` (`idTema`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cuestionario`.`Alternativa`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cuestionario`.`Alternativa` (
  `idAlternativa` INT NOT NULL,
  `Desc_Alter` VARCHAR(45) NULL,
  `Preguntas_idPreguntas` INT NOT NULL,
  `Resp_Correcta` TINYINT(1) NULL,
  `Alternativacol` VARCHAR(45) NULL,
  PRIMARY KEY (`idAlternativa`),
  INDEX `fk_Alternativa_Preguntas1_idx` (`Preguntas_idPreguntas` ASC) VISIBLE,
  CONSTRAINT `fk_Alternativa_Preguntas1`
    FOREIGN KEY (`Preguntas_idPreguntas`)
    REFERENCES `cuestionario`.`Preguntas` (`idPreguntas`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cuestionario`.`Intento`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cuestionario`.`Intento` (
  `idIntento` INT NOT NULL,
  `Desc_Intento` VARCHAR(45) NULL,
  `Resp_Correcta` TINYINT(1) NULL,
  `idUsuario` INT NOT NULL,
  `idPreguntas` INT NOT NULL,
  PRIMARY KEY (`idIntento`),
  INDEX `fk_Detalle_Usuario1_idx` (`idUsuario` ASC) VISIBLE,
  INDEX `fk_Detalle_Preguntas1_idx` (`idPreguntas` ASC) VISIBLE,
  CONSTRAINT `fk_Detalle_Usuario1`
    FOREIGN KEY (`idUsuario`)
    REFERENCES `cuestionario`.`Usuario` (`idUsuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Detalle_Preguntas1`
    FOREIGN KEY (`idPreguntas`)
    REFERENCES `cuestionario`.`Preguntas` (`idPreguntas`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cuestionario`.`Puntuacion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cuestionario`.`Puntuacion` (
  `idPuntuacion` INT NOT NULL,
  `Puntaje` VARCHAR(45) NULL,
  `Usuario_idUsuario` INT NOT NULL,
  `Medalla` VARCHAR(45) NULL,
  PRIMARY KEY (`idPuntuacion`),
  INDEX `fk_Puntuacion_Usuario1_idx` (`Usuario_idUsuario` ASC) VISIBLE,
  CONSTRAINT `fk_Puntuacion_Usuario1`
    FOREIGN KEY (`Usuario_idUsuario`)
    REFERENCES `cuestionario`.`Usuario` (`idUsuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
